### ISSUE TITLE
Document how to interop with JavaScript code/libraries

### ISSUE THREAD

**Issue by mattgallagher92** [fable-compiler/fable-compiler.github.io#181]
I don't think this is in the Fable docs; it would be very useful to have!

When writing custom bindings for JavaScript libraries, I often refer to https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f. There are a few reasons why this isn't ideal:
- It's not as easy to find as it would be if it were in the Fable docs. Newcomers likely don't know it exists.
- It was written in 2017. I don't know whether there have been later changes to Fable which add more alternatives with different tradeoffs.
- It's more verbose than I'd like for a reference (which makes sense - its purpose is to teach, not to be a reference).

A page in the docs would be easier to find, provide more confidence that it's up to date and could be more focused.

**Comment by MangelMaxime** [comment]
To answer your points more specificitly:

> It's not as easy to find as it would be if it were in the Fable docs. Newcomers likely don't know it exists.

True

> It was written in 2017. I don't know whether there have been later changes to Fable which add more alternatives with different tradeoffs.

Indeed, Fable provides alternatives especially around [POJO](https://fable.io/docs/javascript/features.html#plain-old-javascript-objects) most importantly [`[<ParamObject>]`](https://fable.io/docs/javascript/features.html#paramobject)
which I tried to explains the why, and tradeoff / backward compatibility.

I also remember that the Interop guide, guide people in a direction to create more like a library on top of the binding instead of a raw binding which exposes an equivalent API as in JavaScript.

> It's more verbose than I'd like for a reference (which makes sense - its purpose is to teach, not to be a reference).

Fable documentations contains a TOC which I hoped to be used as a reference table to quickly go to the section that matters for the users.

If you have feedbacks regarding the pages or feels like something is missing feel free to tell me via an issue or PR.

**Comment by mattgallagher92** [comment]
Thanks for the quick reply Maxime! And thanks in particular for pointing out the Glutinum specs and `[<ParamObject>]` :slightly_smiling_face: 

Sorry, you're right; I didn't open the "Features" page. I guess, for reasons that I can't explain, I didn't think that the documentation I wanted would be on that page. Perhaps because it had a different name like "calling JS from F#" in an old version of the docs, and I was looking for that.

I think the docs are good as they are :slightly_smiling_face:  sorry for wasting your time :disappointed: 

There could be some value in the things that you suggested, such as the applied example, but I don't think it's necessary for now.

**Comment by MangelMaxime** [comment]
> Sorry, you're right; I didn't open the "Features" page. I guess, for reasons that I can't explain, I didn't think that the documentation I wanted would be on that page. Perhaps because it had a different name like "calling JS from F#" in an old version of the docs, and I was looking for that.

Yes, when doing the rewrite I renamed the page and `Features` is not a perfect name but allows us to have the same structure for all the targets. Which was a requirement for the rewrite of the documentation.

No worries, always happy to help :)
