### ISSUE TITLE
Consider using a github action to automate site deployments

### ISSUE THREAD

**Issue by cartermp** [fable-compiler/fable-compiler.github.io#91]
Upon successful merge to the main branch, there could be an action triggered whenever there is a new commit to that branch. It could then build and deploy the site to the github pages environment. That would speed up updates to the site.

Any thoughts? Happy to help, although I believe I need more permissions to do this myself.

**Comment by MangelMaxime** [comment]
I am totally ok with this idea, it will avoid the need for the maintainer to merge the PR and then clone the repo on their machine + push.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I invited @cartermp as an adamin of this repo (https://github.com/fable-compiler/fable-compiler.github.io).

I don't think the maintainer role would have been enough for him to help setup the github action.

I just fixed the scripts to work on a fresh clone.

In order to publish a new version on a fresh clone we need:
1. `npm i`
1. `npm run deploy`

**Comment by alfonsogarciacaro** [comment]
Definitely, it'd be great to have the website automatically updated when there are new commits to the `dev` branch. Thanks a lot for that!

**Comment by cartermp** [comment]
Accepted! I'll see what I can do today.

**Comment by cartermp** [comment]
Closing! This is now active, and it seems that nothing regressed in the live site after it was deployed.
